apiVersion: v2
name: alfresco-repository
description: Alfresco content repository Helm chart
type: application
version: 0.7.2
appVersion: 23.3.2
dependencies:
  - name: alfresco-common
    version: 3.1.4
    repository: https://alfresco.github.io/alfresco-helm-charts/
  - name: postgresql
    version: 12.5.6
    repository: oci://registry-1.docker.io/bitnamicharts
    tags:
      - ci
