apiVersion: v2
name: alfresco-share
description: Alfresco Share Helm chart for Kubernetes
type: application
version: 2.0.0-alpha.0
appVersion: 25.3.0
dependencies:
  - repository: https://alfresco.github.io/alfresco-helm-charts
    version: 4.0.0
    name: alfresco-common
