---
apiVersion: v2
name: alfresco-common
description: |
  A helper subchart to avoid duplication in alfresco charts and set common
  external dependencies
type: library
version: 3.1.1
dependencies:
  - name: common
    repository: oci://registry-1.docker.io/bitnamicharts
    version: 1.x.x
icon: https://avatars0.githubusercontent.com/u/391127?s=200&v=4
