---
apiVersion: v2
description: A Helm chart providing a basic Apache ActiveMQ deployment required to evaluate ACS (not meant to be used in production).
keywords:
  - activemq
  - message broker
name: activemq
sources:
  - https://github.com/Alfresco/alfresco-helm-charts
version: 3.4.0
appVersion: 5.17.5
dependencies:
  - name: alfresco-common
    version: 3.0.0
    repository: https://alfresco.github.io/alfresco-helm-charts/
icon: https://avatars0.githubusercontent.com/u/391127?s=200&v=4
