apiVersion: v2
name: alfresco-connector-msteams
description: A Helm chart for deploying Alfresco connector msteams service
type: application
version: 2.4.0
appVersion: 2.1.0-A.4
dependencies:
  - name: alfresco-common
    version: 4.0.0
    repository: https://alfresco.github.io/alfresco-helm-charts/
