apiVersion: v2
description: A Helm chart for deploying Alfresco Insight Zeppelin
home: https://www.alfresco.com
icon: https://avatars0.githubusercontent.com/u/391127?s=200&v=4
keywords:
  - zeppelin
  - insight zeppelin
  - alfresco zeppelin
  - alfresco insight zeppelin
name: alfresco-insight-zeppelin
version: 4.0.0-alpha.0
sources:
  - https://github.com/Alfresco/alfresco-helm-charts
appVersion: 2.0.13
dependencies:
  - name: alfresco-common
    version: 3.1.4
    repository: https://alfresco.github.io/alfresco-helm-charts/
