---
apiVersion: v2
description: A Helm chart for deploying Alfresco Search Service
home: https://www.alfresco.com
icon: https://avatars0.githubusercontent.com/u/391127?s=200&v=4
keywords:
  - search
  - search services
  - alfresco search services
  - insight
  - insight engine
  - alfresco insight engine
  - solr
  - alfresco solr
name: alfresco-search-service
sources:
  - https://github.com/Alfresco/alfresco-helm-charts
version: 1.0.2
appVersion: 2.0.6
dependencies:
  - name: alfresco-insight-zeppelin
    version: 2.0.0
    condition: alfresco-insight-zeppelin.enabled
  - name: alfresco-common
    version: 2.0.0
    repository: https://alfresco.github.io/alfresco-helm-charts/
