apiVersion: v2
name: alfresco-connector-hxi
description: A Helm chart for deploying Alfresco connector hxi services
type: application
version: 0.2.1
appVersion: 2.0.2
dependencies:
  - name: alfresco-common
    version: 4.0.0
    repository: https://alfresco.github.io/alfresco-helm-charts/
  - name: activemq
    version: 3.6.2
    repository: https://alfresco.github.io/alfresco-helm-charts/
    tags:
      - ci
  - name: postgresql
    version: 12.5.6
    repository: oci://registry-1.docker.io/bitnamicharts
    tags:
      - ci
