apiVersion: v2
name: alfresco-connector-ms365
description: A Helm chart for deploying Alfresco connector ms365 service
type: application
version: 3.4.0
appVersion: 2.1.0-A.1
dependencies:
  - name: alfresco-common
    version: 4.0.0
    repository: https://alfresco.github.io/alfresco-helm-charts/
